[workspace]
resolver = "3"
members = ["common", "server", "client"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
common = { path = "common" }
serde = { version = "1", features = ["derive"] }
bincode = { version = "2", features = ["serde"] }
proptest = "1"
macroquad = "0.4"
rand = "0.8"
rand_chacha = "0.3"
